### ISSUE TITLE
SVG fix

### ISSUE THREAD

**Issue by jgagne** [ChristinaEEng/Poems#1]
Should have worked: https://github.com/ChristinaEEng/Bits-of-Poems/commit/410cd99e8f64dee9aeef976d8838e7ad56aaf2d5 (Please, try again.)

Before:

 ` <img src="img/poets.png" alt="drawings of various poets." width="100%">`

After:

 `<img src="img/poets.png" srcset="img/poets.svg" alt="drawings of various poets." width="100%">`

`src` becomes the fallback using the PNG ([when `srcset` isn't supported](https://caniuse.com/#search=srcset)) and`srcset` provides the SVG.

**Comment by ChristinaEEng** [comment]
Image still isn't working. I'm not sure whats wrong. I tried re-exporting the files and I put in the code you gave me. But it works locally.

**Comment by jgagne** [comment]
The 2.2 MB file loads faster since it's a local file, but it will load live as well, as shown below:

![poets-svg](https://user-images.githubusercontent.com/5142085/57266347-8c489000-7049-11e9-8228-b71fea469d1c.png)

Also, if you run the PNG through ImageOptim you'll make a much smaller file (475 KB to 263 KB).

Is the originally artwork all drawn as vector? If so, you'll want to save without embedding as an image. If not, maybe just use the PNG, but right now, the SVG you generated is essentially an image embedded within an SVG container, as shown below:

```
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="6600" height="1555" viewBox="0 0 6600 1555">
  <image id="Background" width="6600" height="1555" xlink:href="data:img/png;base64,iVBORw0KGgoAAAANSUhEUgAAGcgAAAYTCAYAAABjyo0GAAAgAElEQVR4nOzdW49W1f3A8WUZhtMMw3BSEA/gtFCrIGCp1qYmtaekJiZ9A03aN9CL3vRl9LoXpklvTJo22sSkF1JrYwk0BRFjUaiKDFSEmWGGw8CA9Z/f6qz5L3f3M4OH7fHzSZ48z7MPa62990MyV3xvevfdd99NAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPAR+5IbCgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAXBHIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA6IRADgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACdEMgBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA…/15VfQCGD/ZhDbKNfAAAAABJRU5ErkJggg=="/>
</svg>
```
